### ISSUE TITLE
December Updates

### ISSUE THREAD

**Issue by mwasham** [Microsoft/MCW-Media-AI#17]
It appears the branding needs to be updated to “Azure Media Services Video Indexer”  
Wording and screenshots need updating 
Azure Portal screenshots need to be updated  
Azure Storage, Cosmos DB, etc

**Comment by DawnmarieDesJardins** [comment]
Adding @Microsoft/media-ai-sme-group 
Adding the SME group for review and discussion

**Comment by brharr** [comment]
I don't know how important you consider the screenshots of the Portal, but the Storage Account creation wizard in the HOL has changed dramatically from the screenshot.

**Comment by brharr** [comment]
HOL: LogicApp creation, you say to Right-Click and choose Open With Logic App Designer - I did not have that extension installed. I had to manually download it and install it before I could do that. This is not an extension that is available by default, there should be some text somewhere that shows the requirement for this extension to be installed.

**Comment by brharr** [comment]
HOL: LogicApp: Create SAS URI by Path - The name of the property is now "List of Files Path". Only the fact that description is the same is what led me to find it.

**Comment by brharr** [comment]
HOL: LogicApp: Step 15 - There is no information on the creating of the connection which has to be done before the location, account id can be filled in. Most users will not have created a connection previously, so there should an added step showing a screenshot of this window.

**Comment by brharr** [comment]
HOL Opening Student Files reference, there is no spot in the document that references the downloading or requirement for the Student Files. It should be referenced somewhere at the top of the document.

**Comment by brharr** [comment]
HOL: Exercise 3: Step 17: Admin WebSite - After setting all of the App Settings and Conn String and publishing, when I refreshed, I get an Exception stating that System.net.Http is missing, but yet it shows in the list of References in VS 2017, but does not show up in packages.config

**Comment by brharr** [comment]
HOL: Task 4: Step 6: misspell, fine = final

**Comment by brharr** [comment]
HOL: Task 4: Step 15 - There is a If statement in the final version of the Run method that is not mentioned anywhere above stating that it needs to be added. I am specifically referring to:

if (inputDocument == null)
    {
        log.Error("'documentId' not found!");
        return req.CreateResponse(HttpStatusCode.BadRequest, $"DocumentId ({input.documentId}) Not Found!");
    }

There is no step to add that in, so somebody may miss it.

**Comment by brharr** [comment]
HOL: Task 4: Step 19 - The publishing and build will not work here, because there is a missing Using statement that is never referenced. With the addition of the GetVideoProcessingState method, there is a need for the JsonConvert function which can be found in the NewtonSoft.Json library. This needs to be added as a step above somewhere before Publishing.

**Comment by DawnmarieDesJardins** [comment]
Notes from Media AI Update meeting on 12/17 @ 3:00 pm (Pacific)

**Scope:**
**What's needed now?**
- Branding update
- Use portal for logic apps & functions
- Admin site - lighten up now - less copy/pasting of code
**What can be added over time?**
- Two different language versions
- Broader use of cognitive search

**Development Timeline**:
- Draft copy due - TBD
     - Jeff to announce draft delivery date by 12/20/18
- SME review - 5 business days for review from draft delivery
- Completed workshop - Estimate end of January

**Comment by olavoborges** [comment]
>           HOL: Exercise 3: Step 17: Admin WebSite - After setting all of the App Settings and Conn String and publishing, when I refreshed, I get an Exception stating that System.net.Http is missing, but yet it shows in the list of References in VS 2017, but does not show up in packages.config.
> I did try adding to packages.config without any success.
> I got this to work finally, but I had to update the NuGet packages for the fourth or fifth time to get it to work and it was not clear that that was required in VS 2017, especially considering that I had already updated the packages 2 or 3 times as it was.

Thank you for raising these issues, they are helping me to go through the workshop sucessfully. Regarding this system.net.http issue, I was able to fix by changing the newVersion to 4.0.0.0

        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.0.0.0" />

**Comment by crpietschmann** [comment]
The use of Logic Apps and Azure Functions has been changed to use the Azure Portal editors for those, rather than Visual Studio.

**Comment by DawnmarieDesJardins** [comment]
January 2019 update merged, closing update issue.
