### ISSUE TITLE
Partition Key is required for Cosmos DB, Function fails

### ISSUE THREAD

**Issue by jussiroine** [Microsoft/MCW-Media-AI#18]
It seems the ability to create Cosmos DB collections without a partition key is now removed from the Azure Portal UI. Thus, the Azure Function in this lab fails:

xception while executing function: Function1
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Function1 ---> System.InvalidOperationException : PartitionKey value must be supplied for this operation.

Could you have a look at what is needed in the Function to have it function properly?

**Comment by crpietschmann** [comment]
This has been addressed in the latest updates.
